### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by refactormyself** [refactormyself/SleazyGumoku#1]
- [ ] Restructure project for and add Maven
- [ ] Add Basic Unit Tests
- [ ] Fix logic Random stone deleted within the newly form set
- [ ] Add logging using a lightweight DB
- [ ] Breakup the project to prepare for a web port (MVC vs MVVM)
